### ISSUE TITLE
Preset request: pharmacies and bike paths

### ISSUE THREAD

**Issue by GalenReich** [bellingcat/osm-search#10]
A user from the [Bellingcat Discord](https://discord.gg/bellingcat) suggested adding presets for pharmacies and bike paths, remarking that they're often well-mapped and pop up a lot in geolocation tasks.

This issue would be closed by adding preset configurations to [frontend/src/assets/queries.js](https://github.com/bellingcat/osm-search/blob/main/frontend/src/assets/queries.js).

**Comment by medium-rare-bagel** [comment]
Hi there! This is the Discord user who suggested the feature. I'd love to take on this task if it's still available. I'm excited about the opportunity to contribute to the project. Pretty straightforward add, but is there any additional context or guidance I should know before I start working on it (always good to ask)? 

Thanks for being so responsive to user feedback and for creating such a welcoming environment for new contributors!

**Comment by GalenReich** [comment]
Hi @medium-rare-bagel - thanks for coming over to GitHub!👋 It absolutely is still available, I'll assign you now! I don't have much additional context to give, this is primarily @loganwilliams project. One thing I expect he'll consider is whether these tags are commonly used to merit inclusion on the list - but it seems like they are!

In the current page design the space for adding new features is limited, but it's possible that this could be changed in the future.

Please do reach out to me here or on Discord if you have any questions or get stuck!

**Comment by GalenReich** [comment]
I spoke to Logan about this and we would definitely welcome a pull request! 🚀

**Comment by medium-rare-bagel** [comment]
Roger that,  will take care after lunch!

**Comment by medium-rare-bagel** [comment]
pull request opened last evening, apologies for the delay!
